### PR TITLE
Create Quiz.html

### PR DESCRIPTION
**Pull request by JayJay247in**
Webpage JavaScript quiz framework. Under improvement......

### CODE REVIEW

**Comment by Abiodun-Shittu** [comment]
@JayJay247in  

kindly create a separate file from the styling and scripting

**Comment by JayJay247in** [comment]
> @JayJay247in  
> 
> kindly create a separate file from the styling and scripting

Oh ok how do I do that?

**Comment by Abiodun-Shittu** [comment]
@JayJay247in 

Also check the existing code, the way the quiz app was structured in [here](https://github.com/tpauldike/js-ES6-react/tree/main/projects/0-quiz_app)

> > @JayJay247in
> > kindly create a separate file from the styling and scripting
> 
> Oh ok how do I do that?

having your style in a file  called `styles.css` then linking it to the html, same with the javascript code in another file called `script.js`

**Comment by JayJay247in** [comment]
> @JayJay247in
> 
> Also check the existing code, the way the quiz app was structured in [here](https://github.com/tpauldike/js-ES6-react/tree/main/projects/0-quiz_app)
> 
> > > @JayJay247in
> > > kindly create a separate file from the styling and scripting
> > 
> > 
> > Oh ok how do I do that?
> 
> having your style in a file called `styles.css` then linking it to the html, same with the javascript code in another file called `script.js`

Ok sir i will do that ASAP

**Comment by JayJay247in** [comment]
> @JayJay247in
> 
> Also check the existing code, the way the quiz app was structured in [here](https://github.com/tpauldike/js-ES6-react/tree/main/projects/0-quiz_app)
> 
> > > @JayJay247in
> > > kindly create a separate file from the styling and scripting
> > 
> > 
> > Oh ok how do I do that?
> 
> having your style in a file called `styles.css` then linking it to the html, same with the javascript code in another file called `script.js`

It is done sir. As you asked

**Comment by tpauldike** [comment]
### Just before I merge this 
You did a great work here. Did you test these codes and confirm that they run well?

Please follow the naming convention and try to conform to the conditions stated in the [terms for contributing](https://github.com/tpauldike/js-ES6-react/blob/main/collaboration_terms.md)

**Comment by JayJay247in** [comment]
> ### Just before I merge this 
> You did a great work here. Did you test these codes and confirm that they run well?
> 
> Please follow the naming convention and try to conform to the conditions stated in the [terms for contributing](https://github.com/tpauldike/js-ES6-react/blob/main/collaboration_terms.md)

Yes sir it is working perfectly

**Pull request merged**
